name: Publish Universal.Utilities.Apps
on: [workflow_dispatch]

jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Publish
          run: |
            Publish-Module -Path .\Utilities\Universal.Utilities.Apps -NuGetApiKey $ENV:NUGETAPIKEY -Repository PSGallery -Verbose
          shell: pwsh
          env:
            NUGETAPIKEY: ${{ secrets.PSGALLERYKEY }}